# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'LoginViewCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginViewCode
  
pod 'SnapKit', '~> 5.0.0'

pod 'FirebaseAuth'
pod 'FirebaseFirestore'
  
end
